# Generated by Django 4.1 on 2023-03-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mthauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='actividad',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='porcentaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='tema',
            field=models.CharField(default='', max_length=30),
        ),
    ]
