# Generated by Django 4.1 on 2023-03-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mthauth', '0002_users_actividad_users_nivel_users_porcentaje_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='session',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
