# Generated by Django 4.1 on 2022-09-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_usuario_apellidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='apellido',
        ),
    ]
